version: '3.8'
services:
  db_vacantes:
    image: postgres:15
    container_name: db_vacantes_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vacantes_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
